"""vendor contacts, minimum order and purchasing terms

Revision ID: 44c932e601b0
Revises: 3de5c4e5def0
Create Date: 2026-09-15 20:21:48.215664+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "44c932e601b0"
down_revision: str | None = "3de5c4e5def0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Hand-checked: Alembic does not compare CHECK constraints, so the two on the
# new vendors columns are written here. The lower(email) expression index on
# vendor_contacts was rendered by autogenerate as a literal column and
# compares correctly under `alembic check`.
# ---------------------------------------------------------------------------


def _create_checks() -> None:
    op.create_check_constraint(
        op.f("ck_vendors_minimum_order_quantity_not_negative"),
        "vendors",
        "minimum_order_quantity is null or minimum_order_quantity >= 0",
    )
    op.create_check_constraint(
        op.f("ck_vendors_minimum_order_value_not_negative"),
        "vendors",
        "minimum_order_value is null or minimum_order_value >= 0",
    )


def _drop_checks() -> None:
    op.drop_constraint(
        op.f("ck_vendors_minimum_order_value_not_negative"), "vendors", type_="check"
    )
    op.drop_constraint(
        op.f("ck_vendors_minimum_order_quantity_not_negative"), "vendors", type_="check"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor_contacts",
        sa.Column("vendor_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "position('@' in email) > 1",
            name=op.f("ck_vendor_contacts_email_looks_like_an_address"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_vendor_contacts_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vendor_contacts_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_vendor_contacts_vendor_id_vendors"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendor_contacts")),
    )
    op.create_index(
        op.f("ix_vendor_contacts_organization_id"),
        "vendor_contacts",
        ["organization_id"],
        unique=False,
    )
    op.create_index("ix_vendor_contacts_vendor_id", "vendor_contacts", ["vendor_id"], unique=False)
    op.create_index(
        "uq_vendor_contacts_primary",
        "vendor_contacts",
        ["vendor_id"],
        unique=True,
        postgresql_where=sa.text("is_primary and is_active"),
    )
    op.create_index(
        "uq_vendor_contacts_vendor_id_lower_email",
        "vendor_contacts",
        ["vendor_id", sa.literal_column("lower(email)")],
        unique=True,
    )
    op.add_column("vendors", sa.Column("minimum_order_quantity", sa.Integer(), nullable=True))
    op.add_column(
        "vendors",
        sa.Column("minimum_order_value", sa.Numeric(precision=12, scale=2), nullable=True),
    )
    op.add_column(
        "vendors",
        sa.Column(
            "purchasing_terms",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    _create_checks()


def downgrade() -> None:
    _drop_checks()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "purchasing_terms")
    op.drop_column("vendors", "minimum_order_value")
    op.drop_column("vendors", "minimum_order_quantity")
    op.drop_index("uq_vendor_contacts_vendor_id_lower_email", table_name="vendor_contacts")
    op.drop_index(
        "uq_vendor_contacts_primary",
        table_name="vendor_contacts",
        postgresql_where=sa.text("is_primary and is_active"),
    )
    op.drop_index("ix_vendor_contacts_vendor_id", table_name="vendor_contacts")
    op.drop_index(op.f("ix_vendor_contacts_organization_id"), table_name="vendor_contacts")
    op.drop_table("vendor_contacts")
    # ### end Alembic commands ###
